export type SimetrixSwitchKind = "bjt_igbt" | "mosfet" | "switch" | "subcircuit";

export type SimetrixComponent = {
  reference: string;
  kind: SimetrixSwitchKind;
  model: string | null;
  lineNumber: number;
  sourceLine: string;
};

export type SimetrixParseResult = {
  components: SimetrixComponent[];
  ignoredLineCount: number;
};

export type SimetrixSweepMode = "same-model" | "all-combinations";

export type SimetrixScriptOptions = {
  references: string[];
  models: string[];
  mode: SimetrixSweepMode;
  netlistFileName: string;
  createNetlistBeforeRun: boolean;
};

const switchKinds: Record<string, SimetrixSwitchKind> = {
  Q: "bjt_igbt",
  M: "mosfet",
  S: "switch",
  X: "subcircuit",
};

export function parseSimetrixNetlist(text: string): SimetrixParseResult {
  const components = new Map<string, SimetrixComponent>();
  let ignoredLineCount = 0;

  text.split(/\r?\n/).forEach((line, index) => {
    const trimmed = stripInlineComment(line).trim();
    if (!trimmed || trimmed.startsWith("*") || trimmed.startsWith(".") || trimmed.startsWith("+")) {
      ignoredLineCount += 1;
      return;
    }

    const tokens = trimmed.split(/\s+/);
    const reference = tokens[0];
    const prefix = reference.charAt(0).toUpperCase();
    const kind = switchKinds[prefix];
    if (!kind || !/^[A-Za-z][A-Za-z0-9_$.-]*$/.test(reference)) {
      ignoredLineCount += 1;
      return;
    }

    if (!components.has(reference)) {
      components.set(reference, {
        reference,
        kind,
        model: extractModelToken(kind, tokens),
        lineNumber: index + 1,
        sourceLine: line.trim(),
      });
    }
  });

  return {
    components: [...components.values()].sort((left, right) =>
      left.reference.localeCompare(right.reference, undefined, { numeric: true }),
    ),
    ignoredLineCount,
  };
}

export function normalizeModelList(text: string): string[] {
  const seen = new Set<string>();
  return text
    .split(/[\s,;]+/)
    .map((item) => item.trim().replace(/^['"]|['"]$/g, ""))
    .filter(Boolean)
    .filter((item) => {
      if (seen.has(item)) {
        return false;
      }
      seen.add(item);
      return true;
    });
}

export function generateSimetrixSweepScript(options: SimetrixScriptOptions): string {
  const references = uniqueNonEmpty(options.references);
  const models = uniqueNonEmpty(options.models);
  const netlistFileName = options.netlistFileName.trim() || "design.net";
  if (references.length === 0) {
    throw new Error("At least one component reference is required.");
  }
  if (models.length === 0) {
    throw new Error("At least one model name is required.");
  }

  return options.mode === "same-model"
    ? generateSameModelScript(references, models, netlistFileName, options.createNetlistBeforeRun)
    : generateCombinationScript(references, models, netlistFileName, options.createNetlistBeforeRun);
}

export function countSimetrixRuns(referenceCount: number, modelCount: number, mode: SimetrixSweepMode): number {
  if (referenceCount <= 0 || modelCount <= 0) {
    return 0;
  }
  return mode === "same-model" ? modelCount : modelCount ** referenceCount;
}

function generateSameModelScript(
  references: string[],
  models: string[],
  netlistFileName: string,
  createNetlistBeforeRun: boolean,
): string {
  return [
    "* Auto-generated by EE Tool",
    "* SIMetrix switch-model loss sweep script",
    "",
    `Let models = [${models.map(quoteSimetrixString).join(", ")}]`,
    `Let refs = [${references.map(quoteSimetrixString).join(", ")}]`,
    "",
    "foreach model models",
    "\tforeach ref refs",
    "\t\tLet SetComponentValue(ref & '.value', model)",
    "\tnext",
    "",
    ...netlistAndRunLines(netlistFileName, createNetlistBeforeRun, "\t", "'same-model: ' & model"),
    "next",
    "",
  ].join("\n");
}

function generateCombinationScript(
  references: string[],
  models: string[],
  netlistFileName: string,
  createNetlistBeforeRun: boolean,
): string {
  const cases = buildModelCombinations(references, models);
  const lines = [
    "* Auto-generated by EE Tool",
    "* SIMetrix switch-model loss sweep script",
    "",
  ];

  cases.forEach((modelByReference, index) => {
    const label = references.map((reference) => `${reference}=${modelByReference[reference]}`).join(", ");
    lines.push(`* Case ${index + 1}: ${label}`);
    references.forEach((reference) => {
      lines.push(
        `Let SetComponentValue(${quoteSimetrixString(`${reference}.value`)}, ${quoteSimetrixString(modelByReference[reference])})`,
      );
    });
    lines.push(...netlistAndRunLines(netlistFileName, createNetlistBeforeRun, "", quoteSimetrixString(`case ${index + 1}: ${label}`)));
    lines.push("");
  });

  return lines.join("\n");
}

function buildModelCombinations(references: string[], models: string[]): Record<string, string>[] {
  return references.reduce<Record<string, string>[]>(
    (cases, reference) =>
      cases.flatMap((item) =>
        models.map((model) => ({
          ...item,
          [reference]: model,
        })),
      ),
    [{}],
  );
}

function netlistAndRunLines(
  netlistFileName: string,
  createNetlistBeforeRun: boolean,
  indent: string,
  echoExpression: string,
): string[] {
  const lines = [`${indent}Echo {'Running simulation ' & ${echoExpression}}`];
  if (createNetlistBeforeRun) {
    lines.push(`${indent}Netlist ${netlistFileName}`);
  }
  lines.push(`${indent}run ${netlistFileName}`);
  lines.push("");
  return lines;
}

function extractModelToken(kind: SimetrixSwitchKind, tokens: string[]): string | null {
  if (kind === "subcircuit") {
    const paramsIndex = tokens.findIndex((token) => token.toUpperCase().startsWith("PARAMS:"));
    const modelIndex = paramsIndex > 1 ? paramsIndex - 1 : tokens.length - 1;
    return tokens[modelIndex] ?? null;
  }

  const modelIndex =
    kind === "bjt_igbt"
      ? 4
      : kind === "mosfet" || kind === "switch"
        ? 5
        : tokens.length - 1;
  return tokens[modelIndex] ?? null;
}

function stripInlineComment(line: string): string {
  const semicolonIndex = line.indexOf(";");
  return semicolonIndex >= 0 ? line.slice(0, semicolonIndex) : line;
}

function uniqueNonEmpty(items: string[]): string[] {
  const seen = new Set<string>();
  return items
    .map((item) => item.trim())
    .filter(Boolean)
    .filter((item) => {
      if (seen.has(item)) {
        return false;
      }
      seen.add(item);
      return true;
    });
}

function quoteSimetrixString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}
