services:
  - type: web
    name: ee-tool
    runtime: python
    buildCommand: pip install -r requirements.txt && npm ci && npm run build
    startCommand: python backend/run_api.py
    envVars:
      - key: HOST
        value: 0.0.0.0
